- name: Register the dotnet 3.1 runtime repository, and install required dependencies
  apt:
    deb: https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
- name: Install/update apt packages
  apt: state=latest update_cache=yes
- name: Make sure HTTPS is supported by apt
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes
- name:
  command: add-apt-repository universe
- name: Install ASP.NET core runtime 3.1
  apt:
    name: aspnetcore-runtime-3.1
    state: present
    update_cache: yes